// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consensus/structures.proto

package consensus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operation_Op int32

const (
	// Operations on every values
	Operation_SET    Operation_Op = 0
	Operation_CONCAT Operation_Op = 1
	// Operations on numeric values
	Operation_ADD Operation_Op = 10
	Operation_MUL Operation_Op = 11
	// Operations on set values
	Operation_SADD Operation_Op = 20
	Operation_SREM Operation_Op = 21
)

var Operation_Op_name = map[int32]string{
	0:  "SET",
	1:  "CONCAT",
	10: "ADD",
	11: "MUL",
	20: "SADD",
	21: "SREM",
}
var Operation_Op_value = map[string]int32{
	"SET":    0,
	"CONCAT": 1,
	"ADD":    10,
	"MUL":    11,
	"SADD":   20,
	"SREM":   21,
}

func (x Operation_Op) String() string {
	return proto.EnumName(Operation_Op_name, int32(x))
}
func (Operation_Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_structures_08f3d7062cc30271, []int{2, 0}
}

type Version struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_structures_08f3d7062cc30271, []int{0}
}
func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (dst *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(dst, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Query struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Policy               string               `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	Emitter              string               `protobuf:"bytes,3,opt,name=emitter,proto3" json:"emitter,omitempty"`
	Deadline             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Requirements         map[string]*Version  `protobuf:"bytes,5,rep,name=requirements,proto3" json:"requirements,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Operations           []*Operation         `protobuf:"bytes,6,rep,name=operations,proto3" json:"operations,omitempty"`
	Signature            []byte               `protobuf:"bytes,16,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_structures_08f3d7062cc30271, []int{1}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (dst *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(dst, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Query) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *Query) GetEmitter() string {
	if m != nil {
		return m.Emitter
	}
	return ""
}

func (m *Query) GetDeadline() *timestamp.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

func (m *Query) GetRequirements() map[string]*Version {
	if m != nil {
		return m.Requirements
	}
	return nil
}

func (m *Query) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *Query) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Operation struct {
	Key                  string       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Op                   Operation_Op `protobuf:"varint,2,opt,name=op,proto3,enum=consensus.Operation_Op" json:"op,omitempty"`
	Data                 []byte       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             []byte       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_structures_08f3d7062cc30271, []int{2}
}
func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (dst *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(dst, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Operation) GetOp() Operation_Op {
	if m != nil {
		return m.Op
	}
	return Operation_SET
}

func (m *Operation) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Operation) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Endorsement struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Emitter              string   `protobuf:"bytes,2,opt,name=emitter,proto3" json:"emitter,omitempty"`
	Conditions           []string `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Signature            []byte   `protobuf:"bytes,16,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endorsement) Reset()         { *m = Endorsement{} }
func (m *Endorsement) String() string { return proto.CompactTextString(m) }
func (*Endorsement) ProtoMessage()    {}
func (*Endorsement) Descriptor() ([]byte, []int) {
	return fileDescriptor_structures_08f3d7062cc30271, []int{3}
}
func (m *Endorsement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endorsement.Unmarshal(m, b)
}
func (m *Endorsement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endorsement.Marshal(b, m, deterministic)
}
func (dst *Endorsement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endorsement.Merge(dst, src)
}
func (m *Endorsement) XXX_Size() int {
	return xxx_messageInfo_Endorsement.Size(m)
}
func (m *Endorsement) XXX_DiscardUnknown() {
	xxx_messageInfo_Endorsement.DiscardUnknown(m)
}

var xxx_messageInfo_Endorsement proto.InternalMessageInfo

func (m *Endorsement) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Endorsement) GetEmitter() string {
	if m != nil {
		return m.Emitter
	}
	return ""
}

func (m *Endorsement) GetConditions() []string {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *Endorsement) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type StartCheckpoint struct {
	Queries              []string `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartCheckpoint) Reset()         { *m = StartCheckpoint{} }
func (m *StartCheckpoint) String() string { return proto.CompactTextString(m) }
func (*StartCheckpoint) ProtoMessage()    {}
func (*StartCheckpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_structures_08f3d7062cc30271, []int{4}
}
func (m *StartCheckpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartCheckpoint.Unmarshal(m, b)
}
func (m *StartCheckpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartCheckpoint.Marshal(b, m, deterministic)
}
func (dst *StartCheckpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartCheckpoint.Merge(dst, src)
}
func (m *StartCheckpoint) XXX_Size() int {
	return xxx_messageInfo_StartCheckpoint.Size(m)
}
func (m *StartCheckpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_StartCheckpoint.DiscardUnknown(m)
}

var xxx_messageInfo_StartCheckpoint proto.InternalMessageInfo

func (m *StartCheckpoint) GetQueries() []string {
	if m != nil {
		return m.Queries
	}
	return nil
}

type Proof struct {
	// Types that are valid to be assigned to Content:
	//	*Proof_Query
	//	*Proof_Endorsement
	Content              isProof_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Proof) Reset()         { *m = Proof{} }
func (m *Proof) String() string { return proto.CompactTextString(m) }
func (*Proof) ProtoMessage()    {}
func (*Proof) Descriptor() ([]byte, []int) {
	return fileDescriptor_structures_08f3d7062cc30271, []int{5}
}
func (m *Proof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proof.Unmarshal(m, b)
}
func (m *Proof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proof.Marshal(b, m, deterministic)
}
func (dst *Proof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proof.Merge(dst, src)
}
func (m *Proof) XXX_Size() int {
	return xxx_messageInfo_Proof.Size(m)
}
func (m *Proof) XXX_DiscardUnknown() {
	xxx_messageInfo_Proof.DiscardUnknown(m)
}

var xxx_messageInfo_Proof proto.InternalMessageInfo

type isProof_Content interface {
	isProof_Content()
}

type Proof_Query struct {
	Query *Query `protobuf:"bytes,1,opt,name=query,proto3,oneof"`
}

type Proof_Endorsement struct {
	Endorsement *Endorsement `protobuf:"bytes,2,opt,name=endorsement,proto3,oneof"`
}

func (*Proof_Query) isProof_Content() {}

func (*Proof_Endorsement) isProof_Content() {}

func (m *Proof) GetContent() isProof_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Proof) GetQuery() *Query {
	if x, ok := m.GetContent().(*Proof_Query); ok {
		return x.Query
	}
	return nil
}

func (m *Proof) GetEndorsement() *Endorsement {
	if x, ok := m.GetContent().(*Proof_Endorsement); ok {
		return x.Endorsement
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Proof) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Proof_OneofMarshaler, _Proof_OneofUnmarshaler, _Proof_OneofSizer, []interface{}{
		(*Proof_Query)(nil),
		(*Proof_Endorsement)(nil),
	}
}

func _Proof_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Proof)
	// content
	switch x := m.Content.(type) {
	case *Proof_Query:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Query); err != nil {
			return err
		}
	case *Proof_Endorsement:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Endorsement); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Proof.Content has unexpected type %T", x)
	}
	return nil
}

func _Proof_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Proof)
	switch tag {
	case 1: // content.query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Query)
		err := b.DecodeMessage(msg)
		m.Content = &Proof_Query{msg}
		return true, err
	case 2: // content.endorsement
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Endorsement)
		err := b.DecodeMessage(msg)
		m.Content = &Proof_Endorsement{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Proof_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Proof)
	// content
	switch x := m.Content.(type) {
	case *Proof_Query:
		s := proto.Size(x.Query)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Proof_Endorsement:
		s := proto.Size(x.Endorsement)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type RecoveryRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoveryRequest) Reset()         { *m = RecoveryRequest{} }
func (m *RecoveryRequest) String() string { return proto.CompactTextString(m) }
func (*RecoveryRequest) ProtoMessage()    {}
func (*RecoveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_structures_08f3d7062cc30271, []int{6}
}
func (m *RecoveryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoveryRequest.Unmarshal(m, b)
}
func (m *RecoveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoveryRequest.Marshal(b, m, deterministic)
}
func (dst *RecoveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoveryRequest.Merge(dst, src)
}
func (m *RecoveryRequest) XXX_Size() int {
	return xxx_messageInfo_RecoveryRequest.Size(m)
}
func (m *RecoveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoveryRequest proto.InternalMessageInfo

func (m *RecoveryRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RecoveryResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version              *Version `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoveryResponse) Reset()         { *m = RecoveryResponse{} }
func (m *RecoveryResponse) String() string { return proto.CompactTextString(m) }
func (*RecoveryResponse) ProtoMessage()    {}
func (*RecoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_structures_08f3d7062cc30271, []int{7}
}
func (m *RecoveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoveryResponse.Unmarshal(m, b)
}
func (m *RecoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoveryResponse.Marshal(b, m, deterministic)
}
func (dst *RecoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoveryResponse.Merge(dst, src)
}
func (m *RecoveryResponse) XXX_Size() int {
	return xxx_messageInfo_RecoveryResponse.Size(m)
}
func (m *RecoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecoveryResponse proto.InternalMessageInfo

func (m *RecoveryResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RecoveryResponse) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *RecoveryResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Version)(nil), "consensus.Version")
	proto.RegisterType((*Query)(nil), "consensus.Query")
	proto.RegisterMapType((map[string]*Version)(nil), "consensus.Query.RequirementsEntry")
	proto.RegisterType((*Operation)(nil), "consensus.Operation")
	proto.RegisterType((*Endorsement)(nil), "consensus.Endorsement")
	proto.RegisterType((*StartCheckpoint)(nil), "consensus.StartCheckpoint")
	proto.RegisterType((*Proof)(nil), "consensus.Proof")
	proto.RegisterType((*RecoveryRequest)(nil), "consensus.RecoveryRequest")
	proto.RegisterType((*RecoveryResponse)(nil), "consensus.RecoveryResponse")
	proto.RegisterEnum("consensus.Operation_Op", Operation_Op_name, Operation_Op_value)
}

func init() {
	proto.RegisterFile("consensus/structures.proto", fileDescriptor_structures_08f3d7062cc30271)
}

var fileDescriptor_structures_08f3d7062cc30271 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x5d, 0x4f, 0xd4, 0x40,
	0x14, 0xa5, 0xed, 0x7e, 0xd0, 0x5b, 0x22, 0x75, 0x82, 0xd8, 0x6c, 0xfc, 0xd8, 0xd4, 0x07, 0x37,
	0xd1, 0x94, 0x64, 0x35, 0xc6, 0xf0, 0x62, 0x10, 0xd6, 0xf0, 0x20, 0xae, 0xce, 0xa2, 0xef, 0xa5,
	0xbd, 0xc0, 0x84, 0xdd, 0x99, 0x32, 0x33, 0x25, 0xf6, 0x97, 0xf9, 0xcf, 0x7c, 0x36, 0x33, 0xdd,
	0x2e, 0x45, 0x36, 0xbc, 0xdd, 0x39, 0xf7, 0xf4, 0x7e, 0x9d, 0x53, 0x18, 0x64, 0x82, 0x2b, 0xe4,
	0xaa, 0x54, 0x7b, 0x4a, 0xcb, 0x32, 0xd3, 0xa5, 0x44, 0x95, 0x14, 0x52, 0x68, 0x41, 0xfc, 0x55,
	0x6e, 0xf0, 0xf2, 0x42, 0x88, 0x8b, 0x39, 0xee, 0xd9, 0xc4, 0x59, 0x79, 0xbe, 0xa7, 0xd9, 0x02,
	0x95, 0x4e, 0x17, 0x45, 0xcd, 0x8d, 0x9f, 0x43, 0xff, 0x17, 0x4a, 0xc5, 0x04, 0x27, 0x04, 0x3a,
	0x97, 0xa9, 0xba, 0x8c, 0x9c, 0xa1, 0x33, 0xda, 0xa2, 0x36, 0x8e, 0xff, 0xba, 0xd0, 0xfd, 0x51,
	0xa2, 0xac, 0x4c, 0xb6, 0x2c, 0x59, 0x6e, 0xb3, 0x3e, 0xb5, 0x31, 0xd9, 0x85, 0x5e, 0x21, 0xe6,
	0x2c, 0xab, 0x22, 0xd7, 0xa2, 0xcb, 0x17, 0x89, 0xa0, 0x8f, 0x0b, 0xa6, 0x35, 0xca, 0xc8, 0xb3,
	0x89, 0xe6, 0x49, 0x3e, 0xc0, 0x66, 0x8e, 0x69, 0x3e, 0x67, 0x1c, 0xa3, 0xce, 0xd0, 0x19, 0x05,
	0xe3, 0x41, 0x52, 0x8f, 0x98, 0x34, 0x23, 0x26, 0xa7, 0xcd, 0x88, 0x74, 0xc5, 0x25, 0x5f, 0x60,
	0x4b, 0xe2, 0x75, 0xc9, 0x24, 0x2e, 0x90, 0x6b, 0x15, 0x75, 0x87, 0xde, 0x28, 0x18, 0xc7, 0xc9,
	0x6a, 0xd3, 0xc4, 0x4e, 0x99, 0xd0, 0x16, 0x69, 0xc2, 0xb5, 0xac, 0xe8, 0x9d, 0xef, 0xc8, 0x7b,
	0x00, 0x51, 0xa0, 0x4c, 0x35, 0x13, 0x5c, 0x45, 0x3d, 0x5b, 0x65, 0xa7, 0x55, 0x65, 0xda, 0x24,
	0x69, 0x8b, 0x47, 0x9e, 0x81, 0xaf, 0xd8, 0x05, 0x4f, 0xcd, 0x91, 0xa3, 0xd0, 0x9e, 0xe7, 0x16,
	0x18, 0xcc, 0xe0, 0xf1, 0xbd, 0xb6, 0x24, 0x04, 0xef, 0x0a, 0xab, 0xe5, 0xb5, 0x4c, 0x48, 0x46,
	0xd0, 0xbd, 0x49, 0xe7, 0x25, 0xda, 0x5b, 0x05, 0x63, 0xd2, 0xea, 0xba, 0x54, 0x80, 0xd6, 0x84,
	0x7d, 0xf7, 0xa3, 0x13, 0xff, 0x71, 0xc0, 0x5f, 0x0d, 0xb3, 0xa6, 0xda, 0x6b, 0x70, 0x45, 0x61,
	0x4b, 0x3d, 0x1a, 0x3f, 0x5d, 0xb7, 0x40, 0x32, 0x2d, 0xa8, 0x2b, 0x0a, 0xa3, 0x5b, 0x9e, 0xea,
	0xd4, 0x0a, 0xb1, 0x45, 0x6d, 0x4c, 0x06, 0xb0, 0xb9, 0x40, 0x9d, 0x5a, 0xbc, 0x63, 0xf1, 0xd5,
	0x3b, 0xfe, 0x04, 0xee, 0xb4, 0x20, 0x7d, 0xf0, 0x66, 0x93, 0xd3, 0x70, 0x83, 0x00, 0xf4, 0x0e,
	0xa7, 0xdf, 0x0e, 0x0f, 0x4e, 0x43, 0xc7, 0x80, 0x07, 0x47, 0x47, 0x21, 0x98, 0xe0, 0xe4, 0xe7,
	0xd7, 0x30, 0x20, 0x9b, 0xd0, 0x99, 0x19, 0x68, 0xc7, 0x46, 0x74, 0x72, 0x12, 0x3e, 0x89, 0x2b,
	0x08, 0x26, 0x3c, 0x17, 0x52, 0xd9, 0x73, 0xac, 0xf5, 0x4d, 0xcb, 0x1f, 0xee, 0x5d, 0x7f, 0xbc,
	0x00, 0xc8, 0x04, 0xcf, 0x59, 0xad, 0x8f, 0x37, 0xf4, 0x46, 0x3e, 0x6d, 0x21, 0x0f, 0x2b, 0x11,
	0xbf, 0x81, 0xed, 0x99, 0x4e, 0xa5, 0x3e, 0xbc, 0xc4, 0xec, 0xaa, 0x10, 0x8c, 0x6b, 0xd3, 0xea,
	0xba, 0x44, 0xc9, 0x50, 0x45, 0x8e, 0xad, 0xd6, 0x3c, 0xe3, 0xdf, 0xd0, 0xfd, 0x2e, 0x85, 0x38,
	0x37, 0xc2, 0x18, 0xac, 0x3e, 0x6f, 0x30, 0x0e, 0xff, 0x37, 0xd5, 0xf1, 0x06, 0xad, 0x09, 0x64,
	0x1f, 0x02, 0xbc, 0x5d, 0x6d, 0x29, 0xe4, 0x6e, 0x8b, 0xdf, 0x5a, 0xfc, 0x78, 0x83, 0xb6, 0xc9,
	0x9f, 0x7d, 0xe8, 0x67, 0x82, 0x6b, 0xe4, 0x3a, 0x7e, 0x05, 0xdb, 0x14, 0x33, 0x71, 0x83, 0xb2,
	0x32, 0xc6, 0x41, 0xa5, 0xef, 0x0b, 0x1c, 0x9f, 0x43, 0x78, 0x4b, 0x52, 0x85, 0x69, 0xb1, 0xc6,
	0x06, 0x6f, 0xa1, 0x7f, 0x53, 0x9b, 0xe7, 0x01, 0x5b, 0x35, 0x94, 0x75, 0x5e, 0x38, 0xeb, 0xd9,
	0xff, 0xee, 0xdd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x84, 0xc0, 0x99, 0x51, 0x04, 0x00,
	0x00,
}
