// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import consensus "github.com/technicolor-research/pnyxdb/consensus"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Key struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71fcc8955c74af3a, []int{0}
}
func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (dst *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(dst, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Value struct {
	Version              *consensus.Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Data                 []byte             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71fcc8955c74af3a, []int{1}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (dst *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(dst, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetVersion() *consensus.Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Value) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71fcc8955c74af3a, []int{2}
}
func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (dst *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(dst, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Values struct {
	Version              *consensus.Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Data                 [][]byte           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Values) Reset()         { *m = Values{} }
func (m *Values) String() string { return proto.CompactTextString(m) }
func (*Values) ProtoMessage()    {}
func (*Values) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71fcc8955c74af3a, []int{3}
}
func (m *Values) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values.Unmarshal(m, b)
}
func (m *Values) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values.Marshal(b, m, deterministic)
}
func (dst *Values) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values.Merge(dst, src)
}
func (m *Values) XXX_Size() int {
	return xxx_messageInfo_Values.Size(m)
}
func (m *Values) XXX_DiscardUnknown() {
	xxx_messageInfo_Values.DiscardUnknown(m)
}

var xxx_messageInfo_Values proto.InternalMessageInfo

func (m *Values) GetVersion() *consensus.Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Values) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Boolean struct {
	Boolean              bool     `protobuf:"varint,1,opt,name=boolean,proto3" json:"boolean,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boolean) Reset()         { *m = Boolean{} }
func (m *Boolean) String() string { return proto.CompactTextString(m) }
func (*Boolean) ProtoMessage()    {}
func (*Boolean) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71fcc8955c74af3a, []int{4}
}
func (m *Boolean) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boolean.Unmarshal(m, b)
}
func (m *Boolean) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boolean.Marshal(b, m, deterministic)
}
func (dst *Boolean) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boolean.Merge(dst, src)
}
func (m *Boolean) XXX_Size() int {
	return xxx_messageInfo_Boolean.Size(m)
}
func (m *Boolean) XXX_DiscardUnknown() {
	xxx_messageInfo_Boolean.DiscardUnknown(m)
}

var xxx_messageInfo_Boolean proto.InternalMessageInfo

func (m *Boolean) GetBoolean() bool {
	if m != nil {
		return m.Boolean
	}
	return false
}

type Transaction struct {
	Policy               string                        `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Deadline             *timestamp.Timestamp          `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Requirements         map[string]*consensus.Version `protobuf:"bytes,3,rep,name=requirements,proto3" json:"requirements,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Operations           []*consensus.Operation        `protobuf:"bytes,4,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71fcc8955c74af3a, []int{5}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *Transaction) GetDeadline() *timestamp.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

func (m *Transaction) GetRequirements() map[string]*consensus.Version {
	if m != nil {
		return m.Requirements
	}
	return nil
}

func (m *Transaction) GetOperations() []*consensus.Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type Receipt struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71fcc8955c74af3a, []int{6}
}
func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (dst *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(dst, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*Key)(nil), "api.Key")
	proto.RegisterType((*Value)(nil), "api.Value")
	proto.RegisterType((*KeyValue)(nil), "api.KeyValue")
	proto.RegisterType((*Values)(nil), "api.Values")
	proto.RegisterType((*Boolean)(nil), "api.Boolean")
	proto.RegisterType((*Transaction)(nil), "api.Transaction")
	proto.RegisterMapType((map[string]*consensus.Version)(nil), "api.Transaction.RequirementsEntry")
	proto.RegisterType((*Receipt)(nil), "api.Receipt")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EndorserClient is the client API for Endorser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EndorserClient interface {
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error)
	Members(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Values, error)
	Contains(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Boolean, error)
	Submit(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Receipt, error)
}

type endorserClient struct {
	cc *grpc.ClientConn
}

func NewEndorserClient(cc *grpc.ClientConn) EndorserClient {
	return &endorserClient{cc}
}

func (c *endorserClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/api.Endorser/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endorserClient) Members(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Values, error) {
	out := new(Values)
	err := c.cc.Invoke(ctx, "/api.Endorser/Members", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endorserClient) Contains(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Boolean, error) {
	out := new(Boolean)
	err := c.cc.Invoke(ctx, "/api.Endorser/Contains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endorserClient) Submit(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Receipt, error) {
	out := new(Receipt)
	err := c.cc.Invoke(ctx, "/api.Endorser/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndorserServer is the server API for Endorser service.
type EndorserServer interface {
	Get(context.Context, *Key) (*Value, error)
	Members(context.Context, *Key) (*Values, error)
	Contains(context.Context, *KeyValue) (*Boolean, error)
	Submit(context.Context, *Transaction) (*Receipt, error)
}

func RegisterEndorserServer(s *grpc.Server, srv EndorserServer) {
	s.RegisterService(&_Endorser_serviceDesc, srv)
}

func _Endorser_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndorserServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Endorser/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndorserServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Endorser_Members_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndorserServer).Members(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Endorser/Members",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndorserServer).Members(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Endorser_Contains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndorserServer).Contains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Endorser/Contains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndorserServer).Contains(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Endorser_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndorserServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Endorser/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndorserServer).Submit(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _Endorser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Endorser",
	HandlerType: (*EndorserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Endorser_Get_Handler,
		},
		{
			MethodName: "Members",
			Handler:    _Endorser_Members_Handler,
		},
		{
			MethodName: "Contains",
			Handler:    _Endorser_Contains_Handler,
		},
		{
			MethodName: "Submit",
			Handler:    _Endorser_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_api_71fcc8955c74af3a) }

var fileDescriptor_api_71fcc8955c74af3a = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0x2f, 0x97, 0xf6, 0x12, 0x27, 0x57, 0xa8, 0x4b, 0xd1, 0x10, 0x28, 0x1e, 0xeb, 0xcb,
	0x29, 0x92, 0x83, 0x28, 0x22, 0x3e, 0x2a, 0x55, 0xf4, 0x10, 0x21, 0x2d, 0x7d, 0xdf, 0x24, 0x63,
	0x59, 0x4c, 0x76, 0xe3, 0xee, 0xa6, 0x90, 0xef, 0xe3, 0x07, 0xf0, 0x23, 0x4a, 0x76, 0x93, 0x33,
	0xda, 0x3e, 0xf9, 0x36, 0xc3, 0xfc, 0xf6, 0x3f, 0xb3, 0xff, 0x3f, 0x9c, 0xb0, 0x96, 0xef, 0x58,
	0xcb, 0xd3, 0x56, 0x49, 0x23, 0x89, 0xcf, 0x5a, 0x9e, 0x24, 0xa5, 0x14, 0x1a, 0x85, 0xee, 0xf4,
	0x4e, 0x1b, 0xd5, 0x95, 0xa6, 0x53, 0xa8, 0x1d, 0x90, 0x3c, 0xb9, 0x91, 0xf2, 0xa6, 0xc6, 0x9d,
	0xed, 0x8a, 0xee, 0xdb, 0xce, 0xf0, 0x06, 0xb5, 0x61, 0x4d, 0xeb, 0x00, 0xfa, 0x18, 0xfc, 0x3d,
	0xf6, 0xe4, 0x14, 0xfc, 0xef, 0xd8, 0xc7, 0xde, 0xc6, 0xdb, 0x3e, 0xc8, 0x87, 0x92, 0x7e, 0x82,
	0xe3, 0x6b, 0x56, 0x77, 0x48, 0x5e, 0x40, 0x70, 0x8b, 0x4a, 0x73, 0x29, 0xec, 0x38, 0xca, 0x48,
	0x7a, 0x58, 0x98, 0x5e, 0xbb, 0x49, 0x3e, 0x21, 0x84, 0xc0, 0x51, 0xc5, 0x0c, 0x8b, 0x97, 0x1b,
	0x6f, 0xbb, 0xce, 0x6d, 0x4d, 0x33, 0x08, 0xf7, 0xd8, 0x3b, 0xb5, 0x3b, 0x8b, 0xc8, 0x19, 0x1c,
	0xdf, 0x0e, 0xa3, 0xf1, 0x89, 0x6b, 0xe8, 0x67, 0x58, 0xd9, 0x07, 0xfa, 0xbf, 0xf7, 0xfb, 0x87,
	0xfd, 0x4f, 0x21, 0x78, 0x27, 0x65, 0x8d, 0x4c, 0x90, 0x18, 0x82, 0xc2, 0x95, 0x56, 0x2c, 0xcc,
	0xa7, 0x96, 0xfe, 0x5a, 0x42, 0x74, 0xa5, 0x98, 0xd0, 0xac, 0x34, 0x83, 0xd0, 0x23, 0x58, 0xb5,
	0xb2, 0xe6, 0xe5, 0x74, 0xeb, 0xd8, 0x91, 0xd7, 0x10, 0x56, 0xc8, 0xaa, 0x9a, 0x0b, 0x77, 0x71,
	0x94, 0x25, 0xa9, 0x33, 0x39, 0x9d, 0x4c, 0x4e, 0xaf, 0x26, 0x93, 0xf3, 0x03, 0x4b, 0x3e, 0xc0,
	0x5a, 0xe1, 0x8f, 0x8e, 0x2b, 0x6c, 0x50, 0x18, 0x1d, 0xfb, 0x1b, 0x7f, 0x1b, 0x65, 0x34, 0x1d,
	0xc2, 0x9c, 0xed, 0x4d, 0xf3, 0x19, 0x74, 0x21, 0x8c, 0xea, 0xf3, 0xbf, 0xde, 0x91, 0x57, 0x00,
	0xb2, 0x45, 0xc5, 0x06, 0x58, 0xc7, 0x47, 0x56, 0xe5, 0x6c, 0xe6, 0xc8, 0xd7, 0x69, 0x98, 0xcf,
	0xb8, 0xe4, 0x12, 0x1e, 0xde, 0x11, 0xbe, 0x27, 0x8b, 0xed, 0x3c, 0x8b, 0xfb, 0x9d, 0x76, 0xc0,
	0xdb, 0xe5, 0x1b, 0x8f, 0x9e, 0x43, 0x90, 0x63, 0x89, 0xbc, 0x35, 0x83, 0xed, 0x5d, 0xc7, 0xab,
	0x51, 0xcb, 0xd6, 0xd9, 0x4f, 0x0f, 0xc2, 0x0b, 0x51, 0x49, 0xa5, 0x51, 0x91, 0x73, 0xf0, 0x3f,
	0xa2, 0x21, 0xa1, 0xfd, 0xef, 0x1e, 0xfb, 0x04, 0x6c, 0x65, 0x33, 0xa6, 0x0b, 0x42, 0x21, 0xf8,
	0x82, 0x4d, 0x81, 0x4a, 0xcf, 0x90, 0xe8, 0x0f, 0xa2, 0xe9, 0x82, 0x3c, 0x83, 0xf0, 0xbd, 0x14,
	0x86, 0x71, 0xa1, 0xc9, 0xc9, 0x04, 0xd9, 0x69, 0xb2, 0xb6, 0xed, 0x18, 0x32, 0x5d, 0x90, 0xe7,
	0xb0, 0xba, 0xec, 0x8a, 0x86, 0x1b, 0x72, 0xfa, 0xaf, 0xc1, 0x23, 0x3b, 0x1e, 0x4e, 0x17, 0xc5,
	0xca, 0xc6, 0xf6, 0xf2, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x9e, 0xb5, 0x49, 0x5b, 0x03,
	0x00, 0x00,
}
